### ISSUE TITLE
Warn about use of object type spread

### ISSUE THREAD

**Issue by jnv** [grubersjoe/reflow#9]
The Flow codebase I work with uses [object type spread](https://flow.org/en/docs/types/objects/#toc-exact-object-types) heavily. Unfortunately this is not ([yet](https://github.com/microsoft/TypeScript/issues/10727)) supported by TypeScript, so I don't expect any straightforward conversion here.

Currently Reflow silently drops the spreaded type, e.g. this:

```js
type CustomProps = {|
  foo: string,
|}

type Props = {|
  ...CustomProps,
  bar: string,
|}
```
is converted to this:

```ts
type CustomProps = {
  foo: string,
}

type Props = {
  bar: string,
}
```

I think Reflow CLI could warn the user about the use of spread syntax. Also the README could mention that the syntax is not supported. What do you think?

**Comment by grubersjoe** [comment]
Thank you for your feedback! Of course properties should not simply be dropped silently. So I added a warning and adapted the README as you suggested :+1:.

Reopen the issue if there are still problems.
